- name: scratchcard
  in: path
  description: Number of scratchcard
  required: true
  schema: {}
- name: given_name
  in: path
  description: Name
  required: true
  schema: {}
- name: surname_1
  in: path
  description: First surname
  required: true
  schema: {}
- name: surname_2
  in: path
  description: Last surname
  required: true
  schema: {}
- name: serial_number
  in: path
  description: Document number
  required: true
  schema: {}
- name: email
  in: path
  description: Email of the certificate owner
  required: true
  schema: {}
- name: mobile_phone_number
  in: path
  description: Phone number of the certificate owner
  required: true
  schema: {}
- name: registration_authority
  in: path
  description: Registration Authority number where certificate belongs
  required: true
  schema: {}